#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          tt-rss
# Required-Start:    $local_fs $syslog $network
# Required-Stop:     $local_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tiny Tiny RSS news reader
# Description:       provides a new reader. The daemon fetch feeds news.
### END INIT INFO
#
set -eu

TTRSS_UPDATE=/var/lib/tt-rss/update_daemon2.php
TTRSS_USER=www-data
TTRSS_NAME=update_daemon2
RUNDIR=/var/run/tt-rss
PIDFILE=/var/run/tt-rss.pid

test -x "$TTRSS_UPDATE" || exit 0

START_DAEMON=true
#test -f $DEBIANCONFIG && . $DEBIANCONFIG

. /lib/lsb/init-functions

is_true()
{
  case "${1:-}" in
    [Yy]es|[Yy]|1|[Tt]|[Tt]rue) return 0;;
    *) return 1;
  esac
}

case "${1:-}" in
  start)
    if is_true $START_DAEMON; then
      log_daemon_msg "Starting TT-RSS feed update service"
      mkdir -p $RUNDIR
      set +e
      start-stop-daemon -S --background --make-pidfile --chuid $TTRSS_USER -p $PIDFILE -v --startas $TTRSS_UPDATE
      log_end_msg $?
      set -e
    fi
    ;;
  stop)
    if [ -f $PIDFILE ] ; then
      log_daemon_msg "Stopping TT-RSS feed update service"
      set +e
      start-stop-daemon -K -p $PIDFILE $TTRSS_UPDATE
      rm -f $PIDFILE
      log_end_msg $?
      set -e
    fi
    ;;
  restart|reload|force-reload)
    ${0:-} stop
    ${0:-} start
    ;;

  status)
    status_of_proc -p $PIDFILE $TTRSS_UPDATE $TTRSS_NAME && exit 0 || exit $?
    ;;
  *)
    echo "Usage: ${0:-} {start|stop|restart|reload|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0
